name: hisoblash_usullari
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.0
  adaptive_theme: ^3.5.0
  get: ^4.6.6
  path_provider: ^2.1.2
  zoom_tap_animation: ^1.1.0
  hive: ^2.2.3
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9

  math_expressions: ^2.4.0
  equations: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/images/

